### ISSUE TITLE
软件自动跳转

### ISSUE THREAD

**Issue by otokaz** [709924470/FanboxViewer#10]
华为手机打开beta-1.3.0版本（最新的那个）会直接跳转到应用详情，根本没法打开，请问这个需要如何解决呢

**Comment by otokaz** [comment]
接上 我用安卓模拟器对7.1,5.1,4.4三个版本的安卓系统都进行了测试，发现都不行

**Comment by npofsi** [comment]
谢谢反馈，近几天正在测试，可能是 push 顺序又乱了

**Comment by npofsi** [comment]
谢谢反馈，近几天正在测试，可能是 push 顺序又乱了

**Comment by SakuraSiki** [comment]
大佬还继续更吗，好不容易最找到这么方便的手机端呜呜

**Comment by npofsi** [comment]
Fixed in latest release.
