### ISSUE TITLE
使用hosts代理来加速网页加载，优化用户体验

### ISSUE THREAD

**Issue by Grey-Wind** [709924470/FanboxViewer#24]
类似hosts go的原理

**Comment by Grey-Wind** [comment]
![Screenshot_20230525_001751.jpg](https://github.com/709924470/FanboxViewer/assets/98391767/4faeaa11-fd6f-49d3-a93d-1089061206b3)

这是我测试出的最好的加速地址，官方ip解析出来的，亲测加速效果好，可以把这个功能放入设置中

**Comment by 709924470** [comment]
goHost使用了手机VPN方面的设置(如果你是root用户那也应该知道直接改host要root权限), FanboxViewer作为一个看图软件并不应该包含的功能, 请合理使用魔法上网工具
