### ISSUE TITLE
Android8.1闪退

### ISSUE THREAD

**Issue by Dr-Visual-Art** [709924470/FanboxViewer#4]
手机为OPPO A7（好像这机子不怎么好），Android版本为8.1.0。打开软件看到界面的时候就立即闪退了，不知道是不是我的操作不对.........另外很期待这个软件（其实是本人很懒，不想在网页打开fanbox），期待作者的修改，加油！

**Comment by 709924470** [comment]
我没收到邮件这么晚才看到抱歉UwU

软件要求外部读写权限, 先检查一下要求的权限有没有给

如果还是不能用的话我会在下个版本加个报错弹窗

**Comment by Dr-Visual-Art** [comment]
好的😜
