### ISSUE TITLE
更新到beta-1.3.0后，应用图标消失，无法打开

### ISSUE THREAD

**Issue by ha-ku** [709924470/FanboxViewer#8]
1. 我尝试了从以前的老版本升级到1.3.0、直接安装1.3.0和从1.2.0升级到1.3.0，APP均无法显示在桌面上，安装完成的界面也没有打开按钮（类似不可打开的系统组件等的显示效果），只能使用Quick Shortcut Maker等软件强行打开。
2. 打开APP并登陆后，订阅内容显示正常，但侧边栏菜单仍然显示未登录，且有一个报错如图。
![error](https://user-images.githubusercontent.com/18721230/96137799-a91c0f00-0f2f-11eb-88f9-66b1e279169b.jpg)

**Comment by npofsi** [comment]
这个由于描述文件错误导致的 bug 在使用 Action 自动构建发布时已被修复，请去本项目的 Github Action 页面下载最新版。

**Comment by ha-ku** [comment]
> 这个由于描述文件错误导致的 bug 在使用 Action 自动构建发布时已被修复，请去本项目的 Github Action 页面下载最新版。

Github Action 里的版本能正常打开，登录后显示未登录和报错的问题仍然存在
